# **Import des modules nécessaires**

In [26]:
import pandas as pd #pour la manipulation de données
from pathlib import Path #pour la gestion des chemins de fichiers
import spacy #pour le prétraitement de texte
from spacy.lang.fr.stop_words import STOP_WORDS as spacy_stopwords

from bertopic import BERTopic #pour la modélisation de sujets

from umap import UMAP #pour la réduction de dimensionnalité
from hdbscan import HDBSCAN #pour le clustering de BERTopic
from sklearn.cluster import KMeans #pour le clustering de BERTopic

from sklearn.feature_extraction.text import CountVectorizer #pour la vectorisation de texte
from bertopic.vectorizers import ClassTfidfTransformer #pour la vectorisation de texte spécifique à BERTopic

from sentence_transformers import SentenceTransformer #pour les embeddings de phrases

# **Chargement du corpus de Zola et de spacy**

In [27]:
df=pd.read_csv(Path("..") /"data" /"2_processed"/ "02_corpus_zola.csv", encoding="utf-8",)
df.head()

,roman,annee,ordre_romans,paquet_id,texte,nb_mots
0,La joie de vivre.,1884,1,1,Comme six heures sonnaient au coucou de la sal...,265
1,La joie de vivre.,1884,1,2,"Il ajouta, après une hésitation: Tu devrais al...",156
2,La joie de vivre.,1884,1,3,en voilà une morveuse qui peut se flatter de n...,265
3,La joie de vivre.,1884,1,4,Et on s’était à peine rencontré deux ou trois ...,255
4,La joie de vivre.,1884,1,5,Quelques gouttes de pluie volant dans l’ouraga...,188

In [28]:
df.shape

(653, 6)

# **Traitement du Corpus de Zola**

In [29]:
stop_perso = {
    "grand", "petit", "homme", "femme", "jour", "heure", "coup", "œil", "oeil", 
    "main", "bras", "tête", "voix", "milieu", "eau", "terre", "air", "monde", 
    "chose", "nuit", "vie", "enfant", "père", "mère", "fille", "garçon", 
    "monsieur", "madame", "falloir", "aller", "voir", "dire", "faire", 
    "pouvoir", "vouloir", "savoir", "venir", "devoir", "prendre", "donner",
    "oui", "non", "où", "quand", "comment", "bon", "jeune", "vieux", "suite"
}

In [30]:
# Chargement du modèle avec désactivation du 'parser' syntaxique pour gagner en vitesse
# On garde impérativement 'ner' pour repérer les personnages/lieux et 'lemmatizer'
nlp = spacy.load("fr_core_news_lg", disable=["parser"])
nlp.max_length = 2_000_000  

#on convertit en liste
textes_bruts = df["texte"].astype(str).tolist()

textes_nettoyes = []

# Utilisation de nlp.pipe pour traiter les textes par blocs (très rapide)
for doc in nlp.pipe(textes_bruts, batch_size=50): 
    tokens = [] # Liste pour stocker les tokens nettoyés
    
    for token in doc:
        lemme = token.lemma_.lower() # Obtenir le lemme du token en minuscules
        
        if (
            not token.is_stop # Ignorer les stop words spaCy par défaut
            and not token.is_punct # Ignorer la ponctuation
            and not token.like_num # Ignorer les chiffres
            and not token.is_space # Ignorer les espaces vides
            and token.ent_type_ not in ['PER', 'LOC', 'ORG'] # Ignorer les Personnages, Lieux et Organisations
            and token.pos_ in {"NOUN", "ADJ"}  # Garder Noms, Adjectifs ET Verbes
            and len(lemme) > 2 # Ignorer les mots de 1 ou 2 lettres
            and lemme not in stop_perso
        ):
            tokens.append(lemme)
            
    # Rejoindre les tokens validés et les ajouter à la liste finale
    textes_nettoyes.append(" ".join(tokens))

# Application de la liste nettoyée à la nouvelle colonne du DataFrame
df["phrases_lemm"] = textes_nettoyes

# Affichage du résultat
df[["phrases_lemm"]].head()

                                        phrases_lemm
0  coucou salle espoir fauteuil lourd jambe goutt...
1  hésitation coin route pâle colère rencontre pe...
2  morveux bourrique paisible accoutumé violence ...
3  peine fois douleur commerce voyage célébrité m...
4  goutte pluie volant ouragan visage souffle ter...

## **1) Choix du modèle d'embedding**

Ici je vais choisir un modèle d'embedding pré-entraîné pour transformer les textes en vecteurs numériques. Je vais utiliser un modèle de la bibliothèque Sentence Transformers, qui est compatible avec BERTopic.

In [31]:
embedding_model = SentenceTransformer(
    "dangvantuan/sentence-camembert-base"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [32]:
print("Génération des embeddings sémantiques...")
embeddings = embedding_model.encode(df['texte'].tolist(), show_progress_bar=True)

Génération des embeddings sémantiques...

Batches:   0%|          | 0/21 [00:00<?, ?it/s]

## **2) Pipeline de Traitement**

### 3) CountVectorizer et ClassTfidfTransformer avec des stop words personnalisés

In [38]:
hdbscan_model = HDBSCAN( min_cluster_size=10, 
                        min_samples=2, 
                        metric='euclidean', 
                        cluster_selection_method='eom',
                        prediction_data=True)

umap_model = UMAP( n_neighbors=20,
                  n_components=3, 
                  min_dist=0.0, 
                  metric="cosine",
                  random_state=42)


vectorizer_model = CountVectorizer(
    min_df=2,    # Le mot doit apparaître dans au moins 2 segments pour être pris en compte (élimine les fautes ou mots uniques)
    max_df=0.6)

ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=True,
)


topic_model = BERTopic(
    language="french",
    hdbscan_model=hdbscan_model,
    umap_model=umap_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    calculate_probabilities=False,
    verbose=True,
    nr_topics="auto"
)
topics, probs = topic_model.fit_transform(df["phrases_lemm"].tolist(), embeddings= embeddings)

2026-07-08 14:51:12,561 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-08 14:51:13,295 - BERTopic - Dimensionality - Completed ✓
2026-07-08 14:51:13,295 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-08 14:51:13,302 - BERTopic - Cluster - Completed ✓
2026-07-08 14:51:13,302 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-07-08 14:51:13,316 - BERTopic - Representation - Completed ✓
2026-07-08 14:51:13,316 - BERTopic - Topic reduction - Reducing number of topics
2026-07-08 14:51:13,319 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-08 14:51:13,332 - BERTopic - Representation - Completed ✓
2026-07-08 14:51:13,332 - BERTopic - Topic reduction - Reduced number of topics from 24 to 21

In [39]:
new_topics = topic_model.reduce_outliers(
    df["phrases_lemm"].tolist(), 
    topics, 
    strategy="embeddings",
    embeddings=embeddings
)

# Met à jour le modèle avec ces nouveaux thèmes plus propres
topic_model.update_topics(df["phrases_lemm"].tolist(), topics=new_topics)

2026-07-08 14:51:15,941 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

## **3) Topics Présent**

In [40]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,0,100,0_lit_malade_visage_mal,"[lit, malade, visage, mal, chambre, chien, peu...",[curé sentencieux verre docteur souffrance com...
1,1,64,1_cœur_raison_parole_fois,"[cœur, raison, parole, fois, silence, docteur,...",[cruel misérable révolte sang mot abominable m...
2,2,49,2_chambre_lit_porte_silence,"[chambre, lit, porte, silence, table, docteur,...",[minute regard vaisselle table débandade chais...
3,3,38,3_vent_vague_mer_pêcheur,"[vent, vague, mer, pêcheur, galet, pluie, flot...",[misère tempête mai dernier maison falaise mar...
4,4,32,4_franc_idée_mer_fortune,"[franc, idée, mer, fortune, mariage, fils, aff...",[poli pièce bois abondance extraordinaire mot ...
5,5,40,5_ancien_soir_samedi_nouveau,"[ancien, soir, samedi, nouveau, chambre, ménag...",[ancien camarade pensée départ mois nouveau dé...
6,6,36,6_désir_amour_point_odeur,"[désir, amour, point, odeur, chair, joie, pass...",[malaise secousse profond maladie besoin conti...
7,7,43,7_chatte_maison_fois_table,"[chatte, maison, fois, table, patte, bête, jeu...",[planche planche superbe réalité saignant orga...
8,8,39,8_docteur_porte_sage_pauvre,"[docteur, porte, sage, pauvre, cuisine, temps,...",[drôle inutile pluie écart mine revêche bonjou...
9,9,29,9_mort_bougie_lit_sommeil,"[mort, bougie, lit, sommeil, soir, peur, chamb...",[ancien livre médecine peur dos unique sensati...
10,10,20,10_lettre_ciel_soir_plage,"[lettre, ciel, soir, plage, mer, idée, marée, ...",[achèvement travail plage véritable soulagemen...
11,11,21,11_ventre_doigt_corps_gauche,"[ventre, doigt, corps, gauche, douleur, cuisse...",[beau force lit misère raidissement irrésistib...
12,12,25,12_existence_courage_force_heureux,"[existence, courage, force, heureux, lendemain...",[hiver courage fois passion usine novembre peu...
13,13,20,13_foie_remède_cher_malade,"[foie, remède, cher, malade, régime, dernier, ...",[pauvre accès dernier sens docteur maison fami...
14,14,18,14_minute_pied_accès_jambe,"[minute, pied, accès, jambe, douleur, chambre,...",[bonté torture dernier secousse pauvre bête ma...
15,15,18,15_curé_pipe_franc_rire,"[curé, pipe, franc, rire, abbé, dame, cousin, ...",[répugnance inquiet amie bouteille bedeau couv...
16,16,20,16_cuisine_feu_figure_vérité,"[cuisine, feu, figure, vérité, docteur, table,...",[moment abbé bonsoir muet effaré morceau veau ...
17,17,16,17_mort_cœur_joie_plein,"[mort, cœur, joie, plein, point, sorte, plaie,...",[salle cuisine terrasse plein menu objet habit...
18,18,11,18_timbale_pain_franc_argent,"[timbale, pain, franc, argent, notaire, monnai...",[corridor monnaie laine dos facture tante curé...
19,19,14,19_franc_argent_rente_cent,"[franc, argent, rente, cent, compte, tiroir, t...",[désastre chanteau terrible franc rente débâcl...

In [41]:
# Récupération de la dimension temporelle
timestamps = df['paquet_id'].tolist()

# Génération des topics dans le temps
topics_over_time = topic_model.topics_over_time(
    df['phrases_lemm'].tolist(), 
    timestamps, 
    nr_bins=30 
)

topic_model.visualize_topics_over_time(topics_over_time) #topics=themes_interet)

30it [00:00, 140.19it/s]

In [42]:
for topic_id in topic_info["Topic"].head(15):
    if topic_id != -1:
        print("\nTOPIC", topic_id)
        print(topic_model.get_topic(topic_id)[:15])

TOPIC 0
[('lit', np.float64(0.022202621179674115)), ('malade', np.float64(0.018594737666320933)), ('visage', np.float64(0.01836658485288974)), ('mal', np.float64(0.01742432468060245)), ('chambre', np.float64(0.017391135906795356)), ('chien', np.float64(0.017286197508602105)), ('peur', np.float64(0.016440939514285505)), ('face', np.float64(0.01588167103946921)), ('pauvre', np.float64(0.015761590475382056)), ('geste', np.float64(0.015400460524232891))]

TOPIC 1
[('cœur', np.float64(0.026993590916338066)), ('raison', np.float64(0.023393196096141627)), ('parole', np.float64(0.019148216743736523)), ('fois', np.float64(0.018137376052307357)), ('silence', np.float64(0.017456009662523485)), ('docteur', np.float64(0.0172870041727113)), ('mauvais', np.float64(0.017128091929831658)), ('mot', np.float64(0.017058967711189702)), ('sage', np.float64(0.016791585895939622)), ('tante', np.float64(0.015710408696271137))]

TOPIC 2
[('chambre', np.float64(0.03598417230557867)), ('lit', np.float64(0.022528104631522744)), ('porte', np.float64(0.02068930667873532)), ('silence', np.float64(0.020254454771772016)), ('table', np.float64(0.01931001956681963)), ('docteur', np.float64(0.019103195536057233)), ('malade', np.float64(0.017863187029635456)), ('haut', np.float64(0.017434113486545055)), ('bouche', np.float64(0.016307984056164397)), ('pauvre', np.float64(0.016306231821651803))]

TOPIC 3
[('vent', np.float64(0.031052296615452512)), ('vague', np.float64(0.029578916822239457)), ('mer', np.float64(0.028470222789586035)), ('pêcheur', np.float64(0.02217467468372099)), ('galet', np.float64(0.021318376955964276)), ('pluie', np.float64(0.020830541358338915)), ('flot', np.float64(0.019156084068844684)), ('poutre', np.float64(0.018942792329458114)), ('village', np.float64(0.018695076710519044)), ('église', np.float64(0.018383261727691173))]

TOPIC 4
[('franc', np.float64(0.04750797359733734)), ('idée', np.float64(0.029819014556938604)), ('mer', np.float64(0.029712756232015785)), ('fortune', np.float64(0.025764041919543557)), ('mariage', np.float64(0.024809438110134606)), ('fils', np.float64(0.023088578656736074)), ('affaire', np.float64(0.02143635522038099)), ('conseil', np.float64(0.02089364596699334)), ('devis', np.float64(0.019667682674052545)), ('charpentier', np.float64(0.019519882602428283))]

TOPIC 5
[('ancien', np.float64(0.02460933423333789)), ('soir', np.float64(0.023809913743387905)), ('samedi', np.float64(0.020854069732362746)), ('nouveau', np.float64(0.01991967052930855)), ('chambre', np.float64(0.019911668274003952)), ('ménage', np.float64(0.01906481864793351)), ('maison', np.float64(0.017577126552582093)), ('matin', np.float64(0.017448086905392533)), ('temps', np.float64(0.017372125680222367)), ('cabriolet', np.float64(0.01655780011139284))]

TOPIC 6
[('désir', np.float64(0.02891628242424025)), ('amour', np.float64(0.02575472968691034)), ('point', np.float64(0.020948754247818665)), ('odeur', np.float64(0.019307764236485295)), ('chair', np.float64(0.018817437423509907)), ('joie', np.float64(0.017686494016576407)), ('passion', np.float64(0.017496707651620938)), ('rire', np.float64(0.016996605396383545)), ('douleur', np.float64(0.01683746697709157)), ('ensemble', np.float64(0.01597204270610765))]

TOPIC 7
[('chatte', np.float64(0.02262044833776315)), ('maison', np.float64(0.020928810136155274)), ('fois', np.float64(0.02019658574198266)), ('table', np.float64(0.017790242321388615)), ('patte', np.float64(0.0175318684697305)), ('bête', np.float64(0.01631483204570135)), ('jeu', np.float64(0.016014349565245882)), ('point', np.float64(0.015957026006759533)), ('morceau', np.float64(0.015340384911014185)), ('doute', np.float64(0.015273628106386473))]

TOPIC 8
[('docteur', np.float64(0.04806556370972245)), ('porte', np.float64(0.040102692024433874)), ('sage', np.float64(0.031125386971044996)), ('pauvre', np.float64(0.02735208089521804)), ('cuisine', np.float64(0.02510586556717573)), ('temps', np.float64(0.023039425697212946)), ('abbé', np.float64(0.022907476577698035)), ('malle', np.float64(0.021257015012012062)), ('médecin', np.float64(0.021187538754917065)), ('sac', np.float64(0.02091375533195442))]

TOPIC 9
[('mort', np.float64(0.032402479024797884)), ('bougie', np.float64(0.02768559310368888)), ('lit', np.float64(0.02554680480456292)), ('sommeil', np.float64(0.024436482076788606)), ('soir', np.float64(0.0243021023718178)), ('peur', np.float64(0.023121134917346645)), ('chambre', np.float64(0.021678158927298092)), ('ombre', np.float64(0.021381921817190033)), ('souffle', np.float64(0.021195746624812526)), ('minute', np.float64(0.020861581422867394))]

TOPIC 10
[('lettre', np.float64(0.03287271811990542)), ('ciel', np.float64(0.02855242882890129)), ('soir', np.float64(0.02446928381402543)), ('plage', np.float64(0.022860355573823116)), ('mer', np.float64(0.022465742516889986)), ('idée', np.float64(0.02238030414648279)), ('marée', np.float64(0.022274941135746042)), ('joie', np.float64(0.021675105610669442)), ('musique', np.float64(0.020657301958073415)), ('foi', np.float64(0.019930091826394474))]

TOPIC 11
[('ventre', np.float64(0.05257121514790607)), ('doigt', np.float64(0.03156165837783821)), ('corps', np.float64(0.030420368747273878)), ('gauche', np.float64(0.02962790011066067)), ('douleur', np.float64(0.02865612207307621)), ('cuisse', np.float64(0.028145287334826036)), ('force', np.float64(0.02675653620310332)), ('peau', np.float64(0.02539534295199486)), ('sang', np.float64(0.02490092291421067)), ('mouvement', np.float64(0.024059870557161477))]

TOPIC 12
[('existence', np.float64(0.023995022864658475)), ('courage', np.float64(0.023839534056746572)), ('force', np.float64(0.021861169938140915)), ('heureux', np.float64(0.020995645006576167)), ('lendemain', np.float64(0.0203450589908932)), ('imbécile', np.float64(0.020022810598081923)), ('cœur', np.float64(0.018034652353706423)), ('tendresse', np.float64(0.017642482575618682)), ('cousin', np.float64(0.017614093583303476)), ('bête', np.float64(0.017334204212383436))]

TOPIC 13
[('foie', np.float64(0.041889963329556704)), ('remède', np.float64(0.031208239453333363)), ('cher', np.float64(0.030480474098430826)), ('malade', np.float64(0.029872521649309078)), ('régime', np.float64(0.02785170175598849)), ('dernier', np.float64(0.02695889102026798)), ('drogue', np.float64(0.02588189942139872)), ('pain', np.float64(0.025588771475531485)), ('gras', np.float64(0.024486635131089056)), ('oreille', np.float64(0.02396116422751341))]

TOPIC 14
[('minute', np.float64(0.03142656944169965)), ('pied', np.float64(0.0303919679904294)), ('accès', np.float64(0.029894871432834636)), ('jambe', np.float64(0.026293887873408795)), ('douleur', np.float64(0.026171155096313212)), ('chambre', np.float64(0.02583825906152453)), ('haut', np.float64(0.025036959969399294)), ('cuisine', np.float64(0.023029440595454427)), ('maison', np.float64(0.023028170657552895)), ('force', np.float64(0.02290902676788263))]