# **Import des modules nécessaires**

In [2]:
import pandas as pd #pour la manipulation de données
from pathlib import Path #pour la gestion des chemins de fichiers
import spacy #pour le prétraitement de texte
from spacy.lang.fr.stop_words import STOP_WORDS as spacy_stopwords

from bertopic import BERTopic #pour la modélisation de sujets

from umap import UMAP #pour la réduction de dimensionnalité
from hdbscan import HDBSCAN #pour le clustering de BERTopic
from sklearn.cluster import KMeans #pour le clustering de BERTopic

from sklearn.feature_extraction.text import CountVectorizer #pour la vectorisation de texte
from bertopic.vectorizers import ClassTfidfTransformer #pour la vectorisation de texte spécifique à BERTopic

from sentence_transformers import SentenceTransformer #pour les embeddings de phrases

# **Chargement du corpus de Zola et de spacy**

In [3]:
df=pd.read_csv(Path("..") /"data" /"2_processed"/ "02_corpus_zola.csv", encoding="utf-8",)
df.head()

,roman,annee,ordre_romans,paquet_id,texte,nb_mots
0,1865 La confession de Claude.,1865,1,1,"Voici l’hiver: l’air, au matin, devient plus f...",214
1,1865 La confession de Claude.,1865,1,2,"La mansarde entière me réclame les rires, les ...",187
2,1865 La confession de Claude.,1865,1,3,Le grillon chantait; le souffle harmonieux des...,146
3,1865 La confession de Claude.,1865,1,4,"brunes et rieuses filles, étaient reines des m...",190
4,1865 La confession de Claude.,1865,1,5,"Pars cependant, puisque tu as soif de la vie. ...",126

In [4]:
df.shape

(21260, 6)

# **Traitement du Corpus de Zola**

In [5]:
stop_perso = {
    "grand", "petit", "homme", "femme", "jour", "heure", "coup", "œil", "oeil", 
    "main", "bras", "tête", "voix", "milieu", "eau", "terre", "air", "monde", 
    "chose", "nuit", "vie", "enfant", "père", "mère", "fille", "garçon", 
    "monsieur", "madame", "falloir", "aller", "voir", "dire", "faire", 
    "pouvoir", "vouloir", "savoir", "venir", "devoir", "prendre", "donner",
    "oui", "non", "où", "quand", "comment", "bon", "jeune", "vieux", "suite"
}

In [6]:
# Chargement du modèle avec désactivation du 'parser' syntaxique pour gagner en vitesse
# On garde impérativement 'ner' pour repérer les personnages/lieux et 'lemmatizer'
nlp = spacy.load("fr_core_news_lg", disable=["parser"])
nlp.max_length = 2_000_000  

#on convertit en liste
textes_bruts = df["texte"].astype(str).tolist()

textes_nettoyes = []

# Utilisation de nlp.pipe pour traiter les textes par blocs (très rapide)
for doc in nlp.pipe(textes_bruts, batch_size=50): 
    tokens = [] # Liste pour stocker les tokens nettoyés
    
    for token in doc:
        lemme = token.lemma_.lower() # Obtenir le lemme du token en minuscules
        
        if (
            not token.is_stop # Ignorer les stop words spaCy par défaut
            and not token.is_punct # Ignorer la ponctuation
            and not token.like_num # Ignorer les chiffres
            and not token.is_space # Ignorer les espaces vides
            and token.ent_type_ not in ['PER', 'LOC', 'ORG'] # Ignorer les Personnages, Lieux et Organisations
            and token.pos_ in {"NOUN", "ADJ"}  # Garder Noms, Adjectifs ET Verbes
            and len(lemme) > 2 # Ignorer les mots de 1 ou 2 lettres
            and lemme not in stop_perso
        ):
            tokens.append(lemme)
            
    # Rejoindre les tokens validés et les ajouter à la liste finale
    textes_nettoyes.append(" ".join(tokens))

# Application de la liste nettoyée à la nouvelle colonne du DataFrame
df["phrases_lemm"] = textes_nettoyes

# Affichage du résultat
df[["phrases_lemm"]].head()

                                        phrases_lemm
0  hiver matin frais manteau brouillard saison so...
1  mansarde entier rire richesse sœur foyer feu j...
2  grillon souffle harmonieux causerie lèvre cœur...
3  brun rieur moisson vendange épi grappe sentier...
4  soif projet soi ferme loyal action rêve vis gr...

## **1) Choix du modèle d'embedding**

Ici je vais choisir un modèle d'embedding pré-entraîné pour transformer les textes en vecteurs numériques. Je vais utiliser un modèle de la bibliothèque Sentence Transformers, qui est compatible avec BERTopic.

In [7]:
embedding_model = SentenceTransformer(
    "dangvantuan/sentence-camembert-base"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [8]:
print("Génération des embeddings sémantiques...")
embeddings = embedding_model.encode(df['texte'].tolist(), show_progress_bar=True)

Génération des embeddings sémantiques...

Batches:   0%|          | 0/665 [00:00<?, ?it/s]

## **2) Pipeline de Traitement**

### 1) HDBSCAN et UMAP

In [28]:
hdbscan_model = HDBSCAN( min_cluster_size=25, min_samples=3, metric='euclidean', cluster_selection_method='eom',prediction_data=True)

umap_model = UMAP( n_neighbors=20,n_components=3, min_dist=0.0, metric="cosine",random_state=42)

### 3) CountVectorizer et ClassTfidfTransformer avec des stop words personnalisés

In [ ]:
hdbscan_model = HDBSCAN( min_cluster_size=25, 
                        min_samples=3, 
                        metric='euclidean', 
                        cluster_selection_method='eom',
                        prediction_data=True)

umap_model = UMAP( n_neighbors=20,
                  n_components=3, 
                  min_dist=0.0, 
                  metric="cosine",
                  random_state=42)


vectorizer_model = CountVectorizer(
    min_df=4,    # Le mot doit apparaître dans au moins 2 segments pour être pris en compte (élimine les fautes ou mots uniques)
    max_df=0.7)

ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=True,
)


topic_model = BERTopic(
    language="french",
    hdbscan_model=hdbscan_model,
    umap_model=umap_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    calculate_probabilities=False,
    verbose=True,
    nr_topics="auto"
)
topics, probs = topic_model.fit_transform(df["phrases_lemm"].tolist(), embeddings= embeddings)

2026-07-08 14:11:09,837 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-08 14:11:19,547 - BERTopic - Dimensionality - Completed ✓
2026-07-08 14:11:19,548 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-08 14:11:19,819 - BERTopic - Cluster - Completed ✓
2026-07-08 14:11:19,820 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2026-07-08 14:11:20,051 - BERTopic - Representation - Completed ✓
2026-07-08 14:11:20,052 - BERTopic - Topic reduction - Reducing number of topics
2026-07-08 14:11:20,069 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-08 14:11:20,268 - BERTopic - Representation - Completed ✓
2026-07-08 14:11:20,270 - BERTopic - Topic reduction - Reduced number of topics from 115 to 55

In [30]:
new_topics = topic_model.reduce_outliers(
    df["phrases_lemm"].tolist(), 
    topics, 
    strategy="embeddings",
    embeddings=embeddings
)

# Met à jour le modèle avec ces nouveaux thèmes plus propres
topic_model.update_topics(df["phrases_lemm"].tolist(), topics=new_topics)

2026-07-08 14:11:49,936 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

## **3) Topics Présent**

In [31]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,0,5024,0_franc_dame_maison_soir,"[franc, dame, maison, soir, mari, porte, fois,...",[face carré nez bec aigle bouche large ferme d...
1,1,1563,1_soleil_noir_haut_blanc,"[soleil, noir, haut, blanc, ciel, ombre, long,...",[pente coteau boisé ville dôme colossal masse ...
2,2,1434,2_amour_cœur_pensée_mort,"[amour, cœur, pensée, mort, tendresse, amant, ...",[coin ombre poltron hagard nouveau individu pa...
3,3,577,3_cœur_larme_heureux_pauvre,"[cœur, larme, heureux, pauvre, bonheur, raison...",[guérie reprise long hérédité perversion démen...
4,4,441,4_porte_lit_chambre_fenêtre,"[porte, lit, chambre, fenêtre, jambe, bruit, p...",[horloge grinça arracher abbé frisson fraîcheu...
5,5,582,5_pauvre_cœur_larme_vou,"[pauvre, cœur, larme, vou, ami, parole, cher, ...",[but secret occasion cher cousin quai désert s...
6,6,269,6_peuple_science_religion_siècle,"[peuple, science, religion, siècle, vérité, ég...",[monument orgueil domination science nom idéal...
7,7,620,7_maman_rire_idée_vrai,"[maman, rire, idée, vrai, bête, chéri, argent,...",[drôle écoute dessert envie mauvais histoire c...
8,8,393,8_abbé_prêtre_curé_affaire,"[abbé, prêtre, curé, affaire, ami, cher, vicai...",[doute matin voyage cardinal secrétaire cardin...
9,9,397,9_franc_fortune_million_argent,"[franc, fortune, million, argent, affaire, mai...",[feuille financier traité année colonne numéro...
10,10,221,10_armée_général_prussien_corps,"[armée, général, prussien, corps, soldat, cano...",[incertitude chef bel résolution premier kilom...
11,11,232,11_amour_cœur_mort_ciel,"[amour, cœur, mort, ciel, souffrance, lèvre, r...",[riche douceur splendeur luxe joie libre amour...
12,12,306,12_voiture_ordre_foule_train,"[voiture, ordre, foule, train, rue, haut, tabl...",[bousculade servante bourgeois paysan accroupi...
13,13,268,13_corps_sang_mort_chambre,"[corps, sang, mort, chambre, lit, froid, noir,...",[couteau pipe table tour menton épaule machine...
14,14,279,14_route_cheval_pied_pain,"[route, cheval, pied, pain, fosse, ouvrier, gr...",[cri bruit course bousculade chef dépendance r...
15,15,379,15_cou_peur_face_cri,"[cou, peur, face, cri, porte, larme, pauvre, b...",[masse cuisse épi mouvement oblique soufflant ...
16,16,170,16_foi_force_espoir_bonheur,"[foi, force, espoir, bonheur, œuvre, miracle, ...",[premier secte chrétien horreur mariage saint ...
17,17,121,17_marbre_pape_temple_haut,"[marbre, pape, temple, haut, soleil, église, p...",[splendeur basilique foule idolâtre cortège su...
18,18,298,18_affaire_prêtre_cardinal_fils,"[affaire, prêtre, cardinal, fils, lettre, dout...",[secrétaire visage fiévreux ardent souffle ass...
19,19,403,19_livre_raison_frère_ami,"[livre, raison, frère, ami, affaire, pauvre, g...",[forme prêt conciliation difficulté terme acco...
20,20,91,20_travail_peuple_bonheur_social,"[travail, peuple, bonheur, social, richesse, o...",[réorganisation travail pacte répartition rich...
21,21,124,21_domaine_œuvre_moisson_peuple,"[domaine, œuvre, moisson, peuple, fécondité, j...",[œuvre œuvre œuvre fécondité victorieux destru...
22,22,267,22_cou_baiser_lèvre_regard,"[cou, baiser, lèvre, regard, gorge, épaule, do...",[instant couverture imaginaire menton tordre m...
23,23,335,23_verre_vin_table_pain,"[verre, vin, table, pain, bouteille, porte, ri...",[demie bande vivre fonctionnaire circonstance ...
24,24,224,24_chambre_porte_meuble_lit,"[chambre, porte, meuble, lit, fenêtre, table, ...",[froid tignasse noir mêler boucle blond bouche...
25,25,154,25_plat_cuisine_table_pain,"[plat, cuisine, table, pain, pomme, morceau, s...",[plat noce boucher déchet viande livre assiett...
26,26,390,26_chambre_porte_soir_maison,"[chambre, porte, soir, maison, lit, dame, tabl...",[figure ciel contente courageux bel appartemen...
27,27,143,27_jambe_pied_corps_épaule,"[jambe, pied, corps, épaule, taille, genou, bo...",[côte désert barque bout écueil compagnon dos ...
28,28,236,28_linge_chemise_chambre_pièce,"[linge, chemise, chambre, pièce, table, armoir...",[bureau redoutable dame question complice crim...
29,29,109,29_barricade_insurgé_national_soldat,"[barricade, insurgé, national, soldat, troupe,...",[misérable douleur remords bourse bruit côté r...
30,30,157,30_amour_autel_orgue_blanc,"[amour, autel, orgue, blanc, soleil, chant, sa...",[sommet tympan gloire ciel fiancé épouse baise...
31,31,132,31_feu_incendie_mort_pied,"[feu, incendie, mort, pied, flamme, échelle, c...",[déchargement affreux pauvre pâleur verdâtre v...
32,32,309,32_porte_abbé_instant_ami,"[porte, abbé, instant, ami, table, salon, huis...",[tranquillité maison honnêteté regard méfiance...
33,33,78,33_peuple_ville_cité_quartier,"[peuple, ville, cité, quartier, maison, palais...",[atavisme constructeur série palais magnifique...
34,34,239,34_prêtre_église_miracle_foi,"[prêtre, église, miracle, foi, saint, divin, c...",[aveugle doux voile vue meilleur simple prière...
35,35,221,35_église_instituteur_frère_foi,"[église, instituteur, frère, foi, justice, vér...",[invention pauvre cerveal moyen peuple abêtir ...
36,36,354,36_travail_maison_pauvre_mari,"[travail, maison, pauvre, mari, idée, bel, ann...",[époque lecture bouquin brocanteur faubourg gé...
37,37,173,37_travail_œuvre_besogne_existence,"[travail, œuvre, besogne, existence, année, us...",[mari petite-fille abîme péril cousin pauvre c...
38,38,105,38_cardinal_abbé_don_eminence,"[cardinal, abbé, don, eminence, prêtre, pape, ...",[rue contretemps voisin recommandation don car...
39,39,88,39_franc_cent_chiffre_million,"[franc, cent, chiffre, million, capital, actio...",[combinaison capital million action nouveau ti...
40,40,157,40_affaire_député_journal_ministre,"[affaire, député, journal, ministre, phrase, a...",[député banc motif majorité commission aigre d...
41,41,146,41_argent_ouvrier_peuple_travail,"[argent, ouvrier, peuple, travail, bonheur, us...",[siècle végétation entêté vivace ancien serf v...
42,42,310,42_table_soir_salle_franc,"[table, soir, salle, franc, salon, soirée, rir...",[charbonnier idée fleuve bière année herscheur...
43,43,337,43_cheveu_face_visage_bel,"[cheveu, face, visage, bel, noir, regard, blan...",[cuillerée constitution délicat mal gras degré...
44,44,202,44_frère_lendemain_maison_fils,"[frère, lendemain, maison, fils, portefaix, mo...",[hasard vue débarquement maître présence ennem...
45,45,308,45_dame_voiture_ami_maison,"[dame, voiture, ami, maison, affaire, cher, po...",[frère conseil municipal conseil municipal rép...
46,46,226,46_nom_cheval_chien_poing,"[nom, cheval, chien, poing, porte, lieutenant,...",[compagnon lassitude résultat noce veille dang...
47,47,218,47_peuple_mort_argent_pain,"[peuple, mort, argent, pain, guerre, misère, o...",[entier fournisseur client bourgeoisie terreur...
48,48,378,48_rire_porte_gros_nez,"[rire, porte, gros, nez, face, soir, coin, fon...",[maison actif ménager nourrice maladroit mater...
49,49,227,49_larme_pauvre_face_lit,"[larme, pauvre, face, lit, docteur, regard, gr...",[docteur papier certificat livret examen génér...
50,50,108,50_peur_poitrine_porte_chambre,"[peur, poitrine, porte, chambre, lèvre, souffr...",[mignon mot mot douceur crainte sol cassé malh...
51,51,283,51_soleil_heureux_joie_rire,"[soleil, heureux, joie, rire, bel, blanc, jard...",[ménage légitime époux amant hasard fiacre rou...
52,52,249,52_président_article_modèle_affaire,"[président, article, modèle, affaire, ministre...",[instant complaisant importance haut puissant ...
53,53,205,53_ombre_silence_mort_porte,"[ombre, silence, mort, porte, noir, bruit, cha...",[âme geste silence ténèbre plafond trône velou...

In [33]:
# Récupération de la dimension temporelle
timestamps = df['annee'].tolist()

# Génération des topics dans le temps
topics_over_time = topic_model.topics_over_time(
    df['phrases_lemm'].tolist(), 
    timestamps, 
    nr_bins=20 
)

topic_model.visualize_topics_over_time(topics_over_time) #topics=themes_interet)

19it [00:02,  7.68it/s]

In [14]:
for topic_id in topic_info["Topic"].head(15):
    if topic_id != -1:
        print("\nTOPIC", topic_id)
        print(topic_model.get_topic(topic_id)[:15])

TOPIC 0
[('amour', np.float64(0.010121056584973942)), ('cœur', np.float64(0.009084831756686123)), ('pensée', np.float64(0.007537823991038832)), ('amant', np.float64(0.007492269292488328)), ('passion', np.float64(0.007370059831349973)), ('chair', np.float64(0.007060846422774702)), ('tendresse', np.float64(0.006947396262719577)), ('désir', np.float64(0.006406614480843874)), ('mort', np.float64(0.0061420202419122825)), ('existence', np.float64(0.005828656694471155))]

TOPIC 1
[('affaire', np.float64(0.007251659850241547)), ('franc', np.float64(0.006924773237352363)), ('fortune', np.float64(0.006550032608275318)), ('instituteur', np.float64(0.0065095866411592354)), ('fils', np.float64(0.006348002448272873)), ('frère', np.float64(0.00585789404700347)), ('année', np.float64(0.005491552267253789)), ('école', np.float64(0.005399147303825323)), ('ancien', np.float64(0.004995309039621288)), ('politique', np.float64(0.00475055834746283))]

TOPIC 2
[('cher', np.float64(0.009487203800158942)), ('dame', np.float64(0.008660161630336614)), ('mari', np.float64(0.007689361372970045)), ('joli', np.float64(0.00744880315616899)), ('ami', np.float64(0.006628576980726366)), ('franc', np.float64(0.006591814297368759)), ('idée', np.float64(0.006500823548246955)), ('affaire', np.float64(0.006467031774344426)), ('porte', np.float64(0.006386790570342916)), ('abbé', np.float64(0.006380763037224333))]

TOPIC 3
[('bonheur', np.float64(0.010707740244036024)), ('raison', np.float64(0.010644625441289657)), ('écoute', np.float64(0.010437144036933311)), ('amour', np.float64(0.009760038222010577)), ('heureux', np.float64(0.009131176691032578)), ('larme', np.float64(0.009033751931717956)), ('tai', np.float64(0.008978774578723803)), ('cœur', np.float64(0.008736396980337654)), ('pauvre', np.float64(0.008657220622807157)), ('chéri', np.float64(0.008532296648520834))]

TOPIC 4
[('horizon', np.float64(0.00951825706961894)), ('arbre', np.float64(0.008914141717340384)), ('ciel', np.float64(0.008866646175322686)), ('soleil', np.float64(0.008521402206306426)), ('gauche', np.float64(0.008271799331835758)), ('vert', np.float64(0.008093462565511958)), ('blanc', np.float64(0.007922763302344062)), ('droite', np.float64(0.007825895428860622)), ('verdure', np.float64(0.007612268417531346)), ('ville', np.float64(0.007138587326627955))]

TOPIC 5
[('franc', np.float64(0.04245014739730084)), ('cent', np.float64(0.020196021840094967)), ('argent', np.float64(0.019267438395959267)), ('billet', np.float64(0.011654407185654221)), ('action', np.float64(0.01121103878971289)), ('million', np.float64(0.011168809811402175)), ('somme', np.float64(0.01071591168882519)), ('chiffre', np.float64(0.010484952807247922)), ('capital', np.float64(0.00965471529183691)), ('affaire', np.float64(0.008592132050074627))]

TOPIC 6
[('peuple', np.float64(0.015451458909535509)), ('religion', np.float64(0.014722053519259542)), ('science', np.float64(0.014637888013172042)), ('catholicisme', np.float64(0.013155272418033676)), ('siècle', np.float64(0.012533148166818825)), ('église', np.float64(0.012174269587017313)), ('pape', np.float64(0.012092168358707338)), ('vérité', np.float64(0.01138996561256831)), ('justice', np.float64(0.011161158013398956)), ('social', np.float64(0.008919877543165273))]

TOPIC 7
[('maman', np.float64(0.015250927019373153)), ('écoute', np.float64(0.009701799797967555)), ('rire', np.float64(0.009369463511972835)), ('mauvais', np.float64(0.008187666499344944)), ('vrai', np.float64(0.008004237864599759)), ('gentil', np.float64(0.007881820057764923)), ('faute', np.float64(0.007855154723281787)), ('mère', np.float64(0.007695827917522993)), ('veu', np.float64(0.007607770770718474)), ('affaire', np.float64(0.0075092393743420825))]

TOPIC 8
[('vou', np.float64(0.012590439550672563)), ('larme', np.float64(0.011676962212491006)), ('cœur', np.float64(0.010548374053098306)), ('pauvre', np.float64(0.009774024387361413)), ('parole', np.float64(0.009361577006145755)), ('ami', np.float64(0.009233893075687559)), ('malheureux', np.float64(0.007917380216979594)), ('amour', np.float64(0.0078067580824035055)), ('prêtre', np.float64(0.007614280418487188)), ('force', np.float64(0.00757634672853636))]

TOPIC 9
[('lit', np.float64(0.02303167299985561)), ('chambre', np.float64(0.015583418373353893)), ('sommeil', np.float64(0.013187041322585264)), ('couverture', np.float64(0.009809789905193371)), ('lampe', np.float64(0.009061926080923752)), ('oreiller', np.float64(0.009055190681716957)), ('drap', np.float64(0.007809832059595706)), ('couche', np.float64(0.007372016231009333)), ('matin', np.float64(0.007283511916260572)), ('pied', np.float64(0.007247945317947932))]

TOPIC 10
[('franc', np.float64(0.011338045645480374)), ('million', np.float64(0.010799441040551664)), ('affaire', np.float64(0.007859463153794894)), ('action', np.float64(0.0076048687553899015)), ('terrain', np.float64(0.00750708777721798)), ('titre', np.float64(0.007403099397711334)), ('argent', np.float64(0.0071146237036287885)), ('fortune', np.float64(0.006816368369908935)), ('société', np.float64(0.006552560488836445)), ('chiffre', np.float64(0.006519642578127032))]

TOPIC 11
[('maman', np.float64(0.012020242839099705)), ('sûr', np.float64(0.009482754081794557)), ('chambre', np.float64(0.00901776611224919)), ('question', np.float64(0.008854286158688603)), ('mari', np.float64(0.00816110999595698)), ('bête', np.float64(0.0080513358329213)), ('porte', np.float64(0.0074083337780411936)), ('colère', np.float64(0.00723098689185476)), ('pauvre', np.float64(0.006895155827190393)), ('cher', np.float64(0.006751413860906777))]

TOPIC 12
[('soleil', np.float64(0.013571953715471787)), ('arbre', np.float64(0.012528423238310127)), ('ombre', np.float64(0.011672462811610707)), ('herbe', np.float64(0.011554039796542223)), ('ciel', np.float64(0.010529628478315655)), ('horizon', np.float64(0.009005344159696766)), ('allée', np.float64(0.008086937492633008)), ('sentier', np.float64(0.0076577089795789)), ('jardin', np.float64(0.007467123769991557)), ('odeur', np.float64(0.007418058321672859))]

TOPIC 13
[('lit', np.float64(0.008645145275564356)), ('mort', np.float64(0.008355968728434778)), ('sang', np.float64(0.0080649716071891)), ('chambre', np.float64(0.007902511338029961)), ('corps', np.float64(0.0077487427243049835)), ('sommeil', np.float64(0.0069019375083944805)), ('ombre', np.float64(0.006670316775961621)), ('chair', np.float64(0.006655901698029531)), ('minute', np.float64(0.006524281889542686)), ('noir', np.float64(0.006438768501331846))]

TOPIC 14
[('jupe', np.float64(0.009643730157060784)), ('robe', np.float64(0.007968350654534015)), ('chemise', np.float64(0.0077612547678009985)), ('cheveu', np.float64(0.007669298861418094)), ('cou', np.float64(0.00687252063213487)), ('blanc', np.float64(0.006417010643790621)), ('pied', np.float64(0.006345928461340897)), ('épaule', np.float64(0.006235854076276099)), ('rose', np.float64(0.006099325521655205)), ('chapeau', np.float64(0.0060017536176466555))]